import Foundation

struct TestGenerator {

    /// Generate an XCUITest that captures screenshots and saves them directly to a shared directory.
    /// Each test method writes a PNG to `screenshotDir/<ScreenName>.png`.
    static func generate(
        screens: [FrameHeroConfig.ScreenConfig],
        bundleId: String,
        screenshotDir: String,
        outputDirectory: URL
    ) throws -> URL {
        let testClassName = "FrameHeroCaptureTests"
        var lines: [String] = []

        lines.append("import XCTest")
        lines.append("")
        lines.append("final class \(testClassName): XCTestCase {")
        lines.append("")

        // Hardcoded output directory (generated by framehero CLI)
        lines.append("    private let outputDir = \"\(screenshotDir)\"")
        lines.append("")

        // Helper: save screenshot to file
        lines.append("    private func saveScreenshot(name: String, app: XCUIApplication) {")
        lines.append("        let screenshot = app.screenshot()")
        lines.append("        let data = screenshot.pngRepresentation")
        lines.append("        let path = (outputDir as NSString).appendingPathComponent(\"\\(name).png\")")
        lines.append("        try? FileManager.default.createDirectory(atPath: outputDir, withIntermediateDirectories: true)")
        lines.append("        FileManager.default.createFile(atPath: path, contents: data)")
        lines.append("    }")
        lines.append("")

        // Helper: find and tap an element, with sidebar/navigation fallback
        lines.append("    private func tapElement(_ label: String, in app: XCUIApplication) {")
        lines.append("        let button = app.buttons[label]")
        lines.append("        if button.waitForExistence(timeout: 3) {")
        lines.append("            button.firstMatch.tap()")
        lines.append("            return")
        lines.append("        }")
        lines.append("        // Element not visible — try opening sidebar/back navigation")
        lines.append("        let backButton = app.navigationBars.buttons.firstMatch")
        lines.append("        if backButton.waitForExistence(timeout: 2) {")
        lines.append("            backButton.tap()")
        lines.append("            sleep(1)")
        lines.append("            let retryButton = app.buttons[label]")
        lines.append("            if retryButton.waitForExistence(timeout: 5) {")
        lines.append("                retryButton.firstMatch.tap()")
        lines.append("                return")
        lines.append("            }")
        lines.append("        }")
        lines.append("        // Last resort: any descendant with this label")
        lines.append("        let any = app.descendants(matching: .any)[label].firstMatch")
        lines.append("        XCTAssertTrue(any.waitForExistence(timeout: 3), \"Could not find element '\\(label)'\")")
        lines.append("        any.tap()")
        lines.append("    }")
        lines.append("")

        for screen in screens {
            let action = try ScreenAction.parse(screen.action)
            let methodName = "testCapture\(sanitize(screen.name))"

            lines.append("    func \(methodName)() {")
            lines.append("        let app = XCUIApplication(bundleIdentifier: \"\(bundleId)\")")
            lines.append("        app.launch()")
            lines.append("        sleep(2)")
            lines.append("")

            switch action {
            case .launch:
                lines.append("        // Capture launch screen")

            case .tap(let label):
                lines.append("        tapElement(\"\(label)\", in: app)")
                lines.append("        sleep(1)")

            case .navigate(let labels):
                for label in labels {
                    lines.append("        tapElement(\"\(label)\", in: app)")
                    lines.append("        sleep(1)")
                }
            }

            lines.append("")
            lines.append("        saveScreenshot(name: \"\(screen.name)\", app: app)")
            lines.append("    }")
            lines.append("")
        }

        lines.append("}")
        lines.append("")

        let content = lines.joined(separator: "\n")
        let filePath = outputDirectory.appendingPathComponent("\(testClassName).swift")

        try FileManager.default.createDirectory(at: outputDirectory, withIntermediateDirectories: true)
        try content.write(to: filePath, atomically: true, encoding: .utf8)

        return filePath
    }

    private static func sanitize(_ name: String) -> String {
        name.replacingOccurrences(of: " ", with: "")
            .replacingOccurrences(of: "-", with: "")
            .replacingOccurrences(of: ".", with: "")
    }
}
