import Foundation

struct TestGenerator {

    /// Generate an XCUITest that captures screenshots and saves them directly to a shared directory.
    /// Each test method writes a PNG to `screenshotDir/<ScreenName>.png`.
    static func generate(
        screens: [FrameHeroConfig.ScreenConfig],
        bundleId: String,
        screenshotDir: String,
        outputDirectory: URL
    ) throws -> URL {
        let testClassName = "FrameHeroCaptureTests"
        var lines: [String] = []

        lines.append("import XCTest")
        lines.append("")
        lines.append("final class \(testClassName): XCTestCase {")
        lines.append("")

        // Hardcoded output directory (generated by framehero CLI)
        lines.append("    private let outputDir = \"\(screenshotDir)\"")
        lines.append("")

        // Helper: save screenshot to file
        lines.append("    private func saveScreenshot(name: String, app: XCUIApplication) {")
        lines.append("        let screenshot = app.screenshot()")
        lines.append("        let data = screenshot.pngRepresentation")
        lines.append("        let path = (outputDir as NSString).appendingPathComponent(\"\\(name).png\")")
        lines.append("        try? FileManager.default.createDirectory(atPath: outputDir, withIntermediateDirectories: true)")
        lines.append("        FileManager.default.createFile(atPath: path, contents: data)")
        lines.append("    }")
        lines.append("")

        // Helper: find and tap an element, with sidebar and index fallback.
        // The fallbackIndex handles localized apps where the label changes
        // but the tab/sidebar position stays the same.
        lines.append("    private func tapElement(_ label: String, fallbackIndex: Int = -1, in app: XCUIApplication) {")
        lines.append("        // Try by label first")
        lines.append("        let button = app.buttons[label]")
        lines.append("        if button.waitForExistence(timeout: 3) {")
        lines.append("            button.firstMatch.tap()")
        lines.append("            return")
        lines.append("        }")
        lines.append("        // Try opening sidebar/back navigation")
        lines.append("        let backButton = app.navigationBars.buttons.firstMatch")
        lines.append("        if backButton.waitForExistence(timeout: 2) {")
        lines.append("            backButton.tap()")
        lines.append("            sleep(1)")
        lines.append("            // Retry by label in sidebar")
        lines.append("            let retryButton = app.buttons[label]")
        lines.append("            if retryButton.waitForExistence(timeout: 3) {")
        lines.append("                retryButton.firstMatch.tap()")
        lines.append("                return")
        lines.append("            }")
        lines.append("            // Label not found (likely translated) — tap by index")
        lines.append("            if fallbackIndex >= 0 {")
        lines.append("                let cells = app.cells")
        lines.append("                if cells.count > fallbackIndex {")
        lines.append("                    cells.element(boundBy: fallbackIndex).tap()")
        lines.append("                    return")
        lines.append("                }")
        lines.append("                let buttons = app.buttons")
        lines.append("                var navButtons: [XCUIElement] = []")
        lines.append("                for i in 0..<buttons.count {")
        lines.append("                    let b = buttons.element(boundBy: i)")
        lines.append("                    let size = b.frame.size")
        lines.append("                    if size.width > 200 && size.height > 30 && size.height < 80 {")
        lines.append("                        navButtons.append(b)")
        lines.append("                    }")
        lines.append("                }")
        lines.append("                if navButtons.count > fallbackIndex {")
        lines.append("                    navButtons[fallbackIndex].tap()")
        lines.append("                    return")
        lines.append("                }")
        lines.append("            }")
        lines.append("        }")
        lines.append("        // Last resort: any descendant")
        lines.append("        let any = app.descendants(matching: .any)[label].firstMatch")
        lines.append("        if any.waitForExistence(timeout: 2) {")
        lines.append("            any.tap()")
        lines.append("            return")
        lines.append("        }")
        lines.append("        XCTFail(\"Could not find element '\\(label)' by label or index\")")
        lines.append("    }")
        lines.append("")

        // Build an index map: each screen gets a sidebar/tab index.
        // Launch occupies index 0, so tap screens start at 1.
        var screenIndex = 0

        for screen in screens {
            let action = try ScreenAction.parse(screen.action)
            let methodName = "testCapture\(sanitize(screen.name))"

            let currentIndex: Int
            switch action {
            case .launch:
                currentIndex = -1 // no fallback needed for launch
                screenIndex += 1
            case .tap, .navigate:
                currentIndex = screenIndex
                screenIndex += 1
            }

            lines.append("    func \(methodName)() {")
            lines.append("        let app = XCUIApplication(bundleIdentifier: \"\(bundleId)\")")
            lines.append("        app.launch()")
            lines.append("        sleep(2)")
            lines.append("")

            switch action {
            case .launch:
                lines.append("        // Capture launch screen")

            case .tap(let label):
                lines.append("        tapElement(\"\(label)\", fallbackIndex: \(currentIndex), in: app)")
                lines.append("        sleep(1)")

            case .navigate(let labels):
                for (i, label) in labels.enumerated() {
                    let idx = i == 0 ? currentIndex : -1
                    lines.append("        tapElement(\"\(label)\", fallbackIndex: \(idx), in: app)")
                    lines.append("        sleep(1)")
                }
            }

            lines.append("")
            lines.append("        saveScreenshot(name: \"\(screen.name)\", app: app)")
            lines.append("    }")
            lines.append("")
        }

        lines.append("}")
        lines.append("")

        let content = lines.joined(separator: "\n")
        let filePath = outputDirectory.appendingPathComponent("\(testClassName).swift")

        try FileManager.default.createDirectory(at: outputDirectory, withIntermediateDirectories: true)
        try content.write(to: filePath, atomically: true, encoding: .utf8)

        return filePath
    }

    private static func sanitize(_ name: String) -> String {
        name.replacingOccurrences(of: " ", with: "")
            .replacingOccurrences(of: "-", with: "")
            .replacingOccurrences(of: ".", with: "")
    }
}
